export const snippets: Record<string, string> = {
  'npm-install': 'npm install tronche',
  'bun-install': 'bun add tronche',
  'pnpm-install': 'pnpm add tronche',
  'yarn-install': 'yarn add tronche',
  'vanilla-import': [
    "import { generateBeamSvg } from 'tronche'",
    '',
    "const svg = generateBeamSvg('Clara Barton', ['#E07A5F', '#3D405B', '#81B29A', '#F4D06F', '#D8A47F'], {",
    '  size: 120,',
    '})',
    "document.getElementById('app')!.innerHTML = svg",
  ].join('\n'),
  'vanilla-html': [
    '<div id="app"></div>',
    '',
    '<script type="module">',
    '  // Using CDN for quick prototyping — use "import { generateBeamSvg } from \'tronche\'" if you installed the package',
    "  import { generateBeamSvg } from 'https://esm.sh/tronche'",
    '',
    "  const svg = generateBeamSvg('Clara Barton', ['#E07A5F', '#3D405B', '#81B29A', '#F4D06F', '#D8A47F'], { size: 200 })",
    "  document.getElementById('app').innerHTML = svg",
    '</script>',
  ].join('\n'),
  'nuxt-config': [
    'export default defineNuxtConfig({',
    "  modules: ['tronche/module'],",
    '})',
  ].join('\n'),
  'nuxt-template': [
    '<template>',
    '  <Avatar name="Maria Mitchell" variant="beam" />',
    '</template>',
  ].join('\n'),
  'vue-import': [
    '<script setup>',
    "import { Avatar } from 'tronche/vue'",
    '</script>',
    '',
    '<template>',
    '  <Avatar name="Grace Hopper" :colors="[',
    "    '#fb6900',",
    "    '#f63700',",
    "    '#004853',",
    '  ]" />',
    '</template>',
  ].join('\n'),
  'curl-example': 'curl "https://tronche.app/api/avatar/Clara%20Barton?variant=beam"',
  'curl-colors': 'curl "https://tronche.app/api/avatar/test?size=200&square=true&colors=FF6B6B,4ECDC4,45B7D1"',
  'home-nuxt': [
    '<template>',
    '  <Avatar name="Clara Barton" variant="beam" />',
    '</template>',
  ].join('\n'),
  'home-vanilla': [
    "import { generateBeamSvg } from 'tronche'",
    '',
    "const svg = generateBeamSvg('Clara Barton', ['#E07A5F', '#3D405B', '#81B29A', '#F4D06F', '#D8A47F'], { size: 120 })",
    "document.getElementById('app')!.innerHTML = svg",
  ].join('\n'),
  'home-vue': [
    '<script setup>',
    "import { Avatar } from 'tronche/vue'",
    '</script>',
    '',
    '<template>',
    '  <Avatar name="Clara Barton" variant="beam" />',
    '</template>',
  ].join('\n'),
  'react-import': [
    "import { Avatar } from 'tronche/react'",
    '',
    'function App() {',
    '  return <Avatar name="Grace Hopper" variant="marble" size={120} />',
    '}',
  ].join('\n'),
  'home-react': [
    "import { Avatar } from 'tronche/react'",
    '',
    'function App() {',
    '  return <Avatar name="Clara Barton" variant="beam" />',
    '}',
  ].join('\n'),
}
