export const snippets: Record<string, string> = {
  'npm-install': 'npm install tronche',
  'vanilla-import': [
    "import { generateBeamSvg } from 'tronche'",
    '',
    "const svg = generateBeamSvg('Clara Barton', ['#E07A5F', '#3D405B', '#81B29A', '#F4D06F', '#D8A47F'], {",
    '  size: 120,',
    '})',
    "// svg: '<svg viewBox=\"0 0 36 36\"...'",
  ].join('\n'),
  'nuxt-config': [
    'export default defineNuxtConfig({',
    "  modules: ['tronche/module'],",
    '})',
  ].join('\n'),
  'nuxt-template': [
    '<template>',
    '  <Avatar name="Maria Mitchell" variant="beam" />',
    '</template>',
  ].join('\n'),
  'vue-import': [
    '<script setup>',
    "import Avatar from 'tronche/vue/components/Avatar.vue'",
    '</script>',
    '',
    '<template>',
    '  <Avatar name="Grace Hopper" :colors="[',
    "    '#fb6900',",
    "    '#f63700',",
    "    '#004853',",
    '  ]" />',
    '</template>',
  ].join('\n'),
  'curl-example': 'curl "https://tronche.app/api/avatar/Clara%20Barton?variant=beam"',
  'curl-colors': 'curl "https://tronche.app/api/avatar/test?size=200&square=true&colors=FF6B6B,4ECDC4,45B7D1"',
  'home-nuxt': [
    '<template>',
    '  <Avatar name="Maria Mitchell" variant="beam" />',
    '</template>',
  ].join('\n'),
}
