import './components/avatar-marble.js'
import './components/avatar-bauhaus.js'
import './components/avatar-beam.js'
import './components/avatar-pixel.js'
import './components/avatar-ring.js'
import './components/avatar-sunset.js'

export { Avatar } from './components/avatar.js'
export type { AvatarVariant } from './components/avatar.js'
export { AvatarMarble } from './components/avatar-marble.js'
export { AvatarBauhaus } from './components/avatar-bauhaus.js'
export { AvatarBeam } from './components/avatar-beam.js'
export { AvatarPixel } from './components/avatar-pixel.js'
export { AvatarRing } from './components/avatar-ring.js'
export { AvatarSunset } from './components/avatar-sunset.js'
